### ISSUE TITLE
MMB examines, instead of switching hands

### ISSUE THREAD

**Issue by verboselucidity** [NEStation-Dev/NEStation_para#16]
Not a glitch, but more of an issue based on what the playerbase prefers.

We can already shift-click to examine, and no MMB hand switch is very inconvenient.

**Comment by MadSnailDisease** [comment]
check click.dm, the code there SHOULD say A.point() for MiddleClickOn(). MiddleClick() should do nothing by default unless someone uncommented that...
this is odd though. my experience shows that it points. Did we edit that file?

**Comment by MadSnailDisease** [comment]
check that _onclick.dm

**Comment by verboselucidity** [comment]
Fixed
