### ISSUE TITLE
Pipe dispensors do not function

### ISSUE THREAD

**Issue by verboselucidity** [NEStation-Dev/NEStation_para#17]
Discovered by CisRox

**Comment by MadSnailDisease** [comment]
is there any other info on this? e.g. does is display a message, dispense the wrong pipe, close the popup?

**Comment by MadSnailDisease** [comment]
idk what the problem was, but everything works fine. Is it possible he caused something to go wrong when he was porting the RPD?

**Comment by MadSnailDisease** [comment]
I tested again, still no problems, closing.
