### ISSUE TITLE
Space Pods will have a "full" drivers' seat.

### ISSUE THREAD

**Issue by javierpwn** [NEStation-Dev/NEStation_para#18]
If you are already in the drivers seat, and right click the pod to get into the pod while already in it, you get into the Passengers' seat, and the Drivers' seat becomes filled with a fake you. occupying it.

**Comment by davikhale** [comment]
/obj/spacepod/verb/move_inside

http://gyazo.com/9a113479b14287f413183772a6c21518

Pods lack specification on moving seats. To move seats you have to "enter the pod" again, which gets stuck in the middle of moving. View screenshot for details.

**Comment by MadSnailDisease** [comment]
so what i have found out:

**Comment by verboselucidity** [comment]
Merged @MadSnailDisease patch
See commit at #23
