### ISSUE TITLE
Minor Spriting Issues

### ISSUE THREAD

**Issue by Cisrox** [NEStation-Dev/NEStation_para#29]
![54f9e874e1ccd563bdd7ca1d1c650947 1](https://cloud.githubusercontent.com/assets/11482753/8635746/2e5b6dce-2803-11e5-8a9b-fa1ccdc189d2.png)

THE GREY GREEN MELONS ARE SUPPOSED TO BE PUMPKINS

WHAAAAT!?!?

THE BERRIES ARE ALL RED!

THE BANANA PLANT HAS A GREEN STEM/TREE SHIT WHATEVER!

PLEASE FIX THE BOTANY SPRITES 

THE BANANAS LOOK LIKE PICKLED PENISES

**Comment by davikhale** [comment]
Cisrox, when opening issue trackers, please use professionalism, and do not use vulgar language. Any issues opened in a similar way will be closed from now on.

Thanks,
Davik
