### ISSUE TITLE
Infinite Incendiary Bats

### ISSUE THREAD

**Issue by Cisrox** [NEStation-Dev/NEStation_para#32]
http://gyazo.com/3b16709dd8aa9c4f9adb83092b8fce23

I managed to make like 6 incendiary bats with one plasma tank.
To reproduce, try making an incendiary bat with ONE rod ON THE GROUND. (shouldn't do anything)
Then make a stack of 10 rods, and create a bat with the rods on the GROUND. Your plasma tank should still be there.

**Comment by verboselucidity** [comment]
Closed, fixed with PR #34
